### ISSUE TITLE
give error about URL

### ISSUE THREAD

**Issue by Yuanchao-Xu** [SantanderMetGroup/ecomsUDG.Raccess#2]
error is like below

http://www.meteo.unican.es/tds5/dodsC/system4/System4_Seasonal_15Members.ncml is not a valid URL

**Comment by jbedia** [comment]
Dear Yuanchao-Xu,
Many thanks for reporting. It seems that the data server is momentarily down for some reason. It will be back soon. 
Sorry for the inconvenience,
cheers
Joaquín
