### ISSUE TITLE
data download/save through ecomsUDG.Raccess

### ISSUE THREAD

**Issue by tanyajn** [SantanderMetGroup/ecomsUDG.Raccess#3]
I have been going through the provided support the websites; 
https://meteo.unican.es/trac/wiki/udg/ecoms and https://github.com/SantanderMetGroup/ecomsUDG.Raccess and I don't see much mention on the possibility of saving/storing the climate data as netcdf or any other format. I only see mention of download from web service. Is there support for saving this climatic data once it is loaded in R memory?
Im new to R!

**Comment by jbedia** [comment]
Dear Tanyajn,

The aforementioned package has been superseded by [loadeR.ECOMS](https://github.com/SantanderMetGroup/loadeR.ECOMS). Please update as no further support is given for ecomsUDG.Raccess.

Regarding your second question, a new addon for loadeR will be released soon (release date planned for next week) to that aim, relying on the ncdf4 R package. Keep an eye on the SantanderMetGroup repo.

cheers

**Comment by jbedia** [comment]
Hi, have a look at  the repo SantanderMetGroup/loadeR.2nc
